spring:
  application:
    name: Order management service API
  
  # Database configuration
  datasource:
    url: jdbc:postgresql://localhost:5432/order_management_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  
  # JPA configuration
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  
  # Cache configuration
  cache:
    type: redis
    redis:
      time-to-live: 600000
      cache-null-values: false
  
  # Redis configuration
  data:
    redis:
      host: localhost
      port: 6379
      repositories:
        enabled: false
      timeout: 60000
      jedis:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0

# Redis keyspace notifications configuration
redis:
  keyspace-notifications:
    enabled: true
    config: "Ex"

# Cache warming configuration
cache:
  warming:
    enabled: true
    recent-days: 30
    min-amount: 100.00
    page-count: 5
    page-size: 20